ALTER TABLE `real-zaragoza-500608.silver.matches`
  ALTER COLUMN match_id SET OPTIONS(description="SofaScore unique match identifier"),
  ALTER COLUMN match_date SET OPTIONS(description="Match date (partition column)"),
  ALTER COLUMN match_round SET OPTIONS(description="Match week or round label within the season"),
  ALTER COLUMN tournament_id SET OPTIONS(description="SofaScore tournament/competition identifier (e.g. 54 = LaLiga2)"),
  ALTER COLUMN season_id SET OPTIONS(description="SofaScore season identifier"),
  ALTER COLUMN league_name SET OPTIONS(description="Human-readable league name"),
  ALTER COLUMN dataset_source SET OPTIONS(description="Origin dataset: standard (pipeline leagues) or wc_26 (FIFA World Cup 2026)"),
  ALTER COLUMN home_team_id SET OPTIONS(description="SofaScore identifier for the home team"),
  ALTER COLUMN home_team_name SET OPTIONS(description="Home team name"),
  ALTER COLUMN away_team_id SET OPTIONS(description="SofaScore identifier for the away team"),
  ALTER COLUMN away_team_name SET OPTIONS(description="Away team name"),
  ALTER COLUMN home_score SET OPTIONS(description="Full-time goals scored by the home team"),
  ALTER COLUMN away_score SET OPTIONS(description="Full-time goals scored by the away team"),
  ALTER COLUMN status SET OPTIONS(description="Match status from SofaScore (e.g. finished, postponed)")
