FROM mcr.microsoft.com/playwright/python:v1.44.0-jammy

WORKDIR /app

COPY requirements-fotmob.txt .
RUN pip install --no-cache-dir -r requirements-fotmob.txt

COPY scraper_fotmob.py .

CMD ["python", "scraper_fotmob.py"]
