# Run from repo root:
#   gcloud builds submit . --config pipeline/cloud-run/docker/cloudbuild-transfermarkt.yaml
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - pipeline/cloud-run/docker/Dockerfile
      - -t
      - europe-west1-docker.pkg.dev/real-zaragoza-500608/rz-images/rz-scraper-transfermarkt:latest
      - .
images:
  - europe-west1-docker.pkg.dev/real-zaragoza-500608/rz-images/rz-scraper-transfermarkt:latest
