real_zaragoza:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: real-zaragoza-500608
      dataset: bronze
      location: europe-west1
      threads: 4
      timeout_seconds: 300
