ALTER TABLE `real-zaragoza-500608.wc_2026.sofascore_shots`
  SET OPTIONS(description="GRAIN: one row per (shot_id, scrape run) — NOT deduplicated. SOURCE: scraper_sofascore.py run with BQ_DATASET=wc_2026. PARTITION BY match_date (DAY). CLUSTER BY match_round. NOTES: FIFA World Cup 2026 shot events only. Tournament ended ~2026-07-19. Merged into bronze.shots via UNION ALL with dataset_source='wc_26'. Identical schema to raw.sofascore_shots — see that table for full column descriptions.");

ALTER TABLE `real-zaragoza-500608.wc_2026.sofascore_shots`
  ALTER COLUMN shot_id SET OPTIONS(description="SofaScore unique shot identifier (string)"),
  ALTER COLUMN match_id SET OPTIONS(description="SofaScore match identifier this shot belongs to"),
  ALTER COLUMN match_date SET OPTIONS(description="Date the match was played (partition key)"),
  ALTER COLUMN match_round SET OPTIONS(description="Round number within the WC 2026 tournament"),
  ALTER COLUMN tournament_id SET OPTIONS(description="SofaScore tournament ID — always '16' for FIFA World Cup"),
  ALTER COLUMN season_id SET OPTIONS(description="SofaScore season ID — always '58210' for WC 2026"),
  ALTER COLUMN league_name SET OPTIONS(description="Always 'FIFA World Cup' for all rows in this table"),
  ALTER COLUMN player_id SET OPTIONS(description="SofaScore player identifier of the shooter"),
  ALTER COLUMN player_name SET OPTIONS(description="Name of the player who took the shot"),
  ALTER COLUMN is_home SET OPTIONS(description="True if the shooter's team was the home side"),
  ALTER COLUMN minute SET OPTIONS(description="Match minute when the shot was taken"),
  ALTER COLUMN added_time SET OPTIONS(description="Added time (stoppage time) minutes, if applicable"),
  ALTER COLUMN time_seconds SET OPTIONS(description="Cumulative match time in seconds when shot was taken"),
  ALTER COLUMN x SET OPTIONS(description="Shooter pitch x-coordinate (0–100 scale, SofaScore system)"),
  ALTER COLUMN y SET OPTIONS(description="Shooter pitch y-coordinate (0–100 scale, SofaScore system)"),
  ALTER COLUMN goal_mouth_x SET OPTIONS(description="Goal-mouth impact x-coordinate (0–100)"),
  ALTER COLUMN goal_mouth_y SET OPTIONS(description="Goal-mouth impact y-coordinate (0–100)"),
  ALTER COLUMN goal_mouth_z SET OPTIONS(description="Goal-mouth impact z-coordinate (height, 0–100)"),
  ALTER COLUMN goal_mouth_location SET OPTIONS(description="Descriptive goal-mouth zone label (e.g. 'HighCentre', 'LowLeft')"),
  ALTER COLUMN block_x SET OPTIONS(description="Block location x-coordinate if blocked (NULL otherwise)"),
  ALTER COLUMN block_y SET OPTIONS(description="Block location y-coordinate if blocked (NULL otherwise)"),
  ALTER COLUMN body_part SET OPTIONS(description="Body part used (e.g. 'rightFoot', 'leftFoot', 'head')"),
  ALTER COLUMN shot_type SET OPTIONS(description="Shot outcome type (e.g. 'goal', 'save', 'miss', 'block', 'post')"),
  ALTER COLUMN situation SET OPTIONS(description="Situation leading to shot (e.g. 'openPlay', 'setpiece', 'fastbreak')"),
  ALTER COLUMN xg SET OPTIONS(description="Expected goals (xG) value for this specific shot (0.0–1.0)"),
  ALTER COLUMN ingested_date SET OPTIONS(description="Calendar date when this row was written by the scraper"),
  ALTER COLUMN ingested_at SET OPTIONS(description="Full ISO timestamp when this row was written by the scraper")
