# Run from repo root:
#   gcloud builds submit pipeline/cloud-run/wage-predictor \
#     --config pipeline/cloud-run/wage-predictor/cloudbuild.yaml
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - europe-west1-docker.pkg.dev/real-zaragoza-500608/rz-images/rz-wage-predictor:latest
      - .
images:
  - europe-west1-docker.pkg.dev/real-zaragoza-500608/rz-images/rz-wage-predictor:latest
