ALTER TABLE `real-zaragoza-500608.gold.agg_rz_squad_finances`
  ALTER COLUMN player_id SET OPTIONS(description="Transfermarkt internal player identifier"),
  ALTER COLUMN name SET OPTIONS(description="Player full name"),
  ALTER COLUMN jersey_number SET OPTIONS(description="Squad jersey number at Real Zaragoza"),
  ALTER COLUMN position SET OPTIONS(description="Transfermarkt position label"),
  ALTER COLUMN age SET OPTIONS(description="Player age at time of latest scrape"),
  ALTER COLUMN date_of_birth SET OPTIONS(description="Player date of birth"),
  ALTER COLUMN nationality SET OPTIONS(description="Primary nationality"),
  ALTER COLUMN height SET OPTIONS(description="Player height in centimetres"),
  ALTER COLUMN foot SET OPTIONS(description="Preferred foot"),
  ALTER COLUMN market_value_eur SET OPTIONS(description="Transfermarkt estimated market value in EUR (table ordered by this descending)"),
  ALTER COLUMN contract_expiry SET OPTIONS(description="Contract expiry date at Real Zaragoza"),
  ALTER COLUMN joined_date SET OPTIONS(description="Date the player joined Zaragoza"),
  ALTER COLUMN signed_from SET OPTIONS(description="Club from which the player was signed"),
  ALTER COLUMN signing_fee SET OPTIONS(description="Reported transfer fee paid by Zaragoza in EUR (NULL if free or undisclosed)"),
  ALTER COLUMN season_id SET OPTIONS(description="Season year string from the Transfermarkt scrape"),
  ALTER COLUMN ingested_date SET OPTIONS(description="Date of the latest scrape")
