CREATE OR REPLACE TABLE `real-zaragoza-500608.gold.fct_player_season_stats`
CLUSTER BY league_name, season_id, primary_position
AS
SELECT
  player_id, player_name,
  ANY_VALUE(position) AS primary_position,
  team_name, league_name, dataset_source, tournament_id, season_id,
  COUNT(DISTINCT match_id)                                                                    AS matches,
  SUM(minutes_played)                                                                         AS total_minutes,
  ROUND(AVG(rating), 2)                                                                       AS avg_rating,
  SUM(goals)                                                                                  AS goals,
  SUM(goal_assists)                                                                           AS assists,
  SUM(total_shots)                                                                            AS shots,
  SUM(shots_on_target)                                                                        AS shots_on_target,
  ROUND(SAFE_DIVIDE(SUM(goals), SUM(total_shots)) * 100, 1)                                  AS conversion_pct,
  ROUND(SUM(goals)        / NULLIF(SUM(minutes_played),0) * 90, 2)                           AS goals_p90,
  ROUND(SUM(goal_assists) / NULLIF(SUM(minutes_played),0) * 90, 2)                           AS assists_p90,
  ROUND(SUM(total_shots)  / NULLIF(SUM(minutes_played),0) * 90, 2)                           AS shots_p90,
  ROUND(AVG(expected_goals), 3)                                                               AS avg_xg_per_match,
  SUM(key_passes)                                                                             AS key_passes,
  ROUND(SUM(key_passes)   / NULLIF(SUM(minutes_played),0) * 90, 2)                           AS key_passes_p90,
  SUM(total_passes)                                                                           AS passes,
  SUM(accurate_passes)                                                                        AS acc_passes,
  ROUND(SAFE_DIVIDE(SUM(accurate_passes),   SUM(total_passes))    * 100, 1)                  AS pass_acc_pct,
  SUM(total_long_balls)                                                                       AS long_balls,
  ROUND(SAFE_DIVIDE(SUM(accurate_long_balls), SUM(total_long_balls)) * 100, 1)               AS long_ball_acc_pct,
  SUM(total_crosses)                                                                          AS crosses,
  ROUND(SAFE_DIVIDE(SUM(accurate_crosses),  SUM(total_crosses))   * 100, 1)                  AS cross_acc_pct,
  SUM(total_tackle)                                                                           AS tackles,
  SUM(won_tackle)                                                                             AS tackles_won,
  ROUND(SAFE_DIVIDE(SUM(won_tackle), SUM(total_tackle)) * 100, 1)                            AS tackle_win_pct,
  SUM(interceptions)                                                                          AS interceptions,
  SUM(total_clearance)                                                                        AS clearances,
  SUM(aerial_won)                                                                             AS aerials_won,
  SUM(aerial_lost)                                                                            AS aerials_lost,
  ROUND(SAFE_DIVIDE(SUM(aerial_won), SUM(aerial_won)+SUM(aerial_lost)) * 100, 1)             AS aerial_win_pct,
  SUM(duel_won)                                                                               AS duels_won,
  SUM(duel_lost)                                                                              AS duels_lost,
  ROUND(SAFE_DIVIDE(SUM(duel_won),  SUM(duel_won)+SUM(duel_lost))  * 100, 1)                 AS duel_win_pct,
  ROUND(SUM(interceptions) / NULLIF(SUM(minutes_played),0) * 90, 2)                         AS interceptions_p90,
  ROUND(SUM(total_tackle)  / NULLIF(SUM(minutes_played),0) * 90, 2)                         AS tackles_p90,
  SUM(touches)                                                                                AS touches,
  ROUND(SUM(touches)       / NULLIF(SUM(minutes_played),0) * 90, 2)                          AS touches_p90,
  SUM(fouls)                                                                                  AS fouls_committed,
  SUM(was_fouled)                                                                             AS fouls_won,
  SUM(yellow_cards)                                                                           AS yellows,
  SUM(red_cards)                                                                              AS reds,
  ROUND(SUM(yellow_cards)  / NULLIF(SUM(minutes_played),0) * 90, 3)                          AS yellows_p90
FROM `real-zaragoza-500608.silver.player_stats`
WHERE minutes_played IS NOT NULL AND minutes_played > 0
GROUP BY player_id, player_name, team_name, league_name, dataset_source, tournament_id, season_id
