CREATE OR REPLACE TABLE `real-zaragoza-500608.rz_gold.gold_tm_players` AS
SELECT
  player_id,
  name,
  club_id,
  club_name,
  club_slug,
  league_name,
  tm_league_code,
  season_id,
  position,
  age,
  date_of_birth,
  nationality,
  nationality_all,
  height,
  foot,
  market_value_eur,
  contract_expiry,
  joined_date,
  signed_from,
  signing_fee,
  jersey_number,
  ingested_date
FROM `real-zaragoza-500608.rz_silver.silver_tm_players`
